openapi: 3.0.0
info:
  version: 1.0.0
  title: Lex-Edu API
  description: API documentation for Lex-Edu Application
servers:
  - url: http://localhost:8000
    description: Server running on local machine with valid .env
  - url: http://localhost:8080
    description: Server running on local machine without valid .env
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /api/auth/register:
    post:
      tags:
        - User Authentication
      summary: Register
      description: New user account registration or creation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - name
                - email
                - password
      responses:
        "201":
          description: New user created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Bad request - User already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal server error - Database error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  